### ISSUE TITLE
Require less `mut`, allow multiple (non-mut) references to Client

### ISSUE THREAD

**Issue by ctron** [Dzordzu/rust-apache-age#11]
The function `execute_cypher` of `Client` requires `&mut self`, which doesn't seem to be required. However, having it `mut` seems to make it impossible to use transactions, as that would also require `&mut self`, which flows into the transaction.

**Comment by Dzordzu** [comment]
I'll look into that in the following week. Thanks for reporting!

**Comment by ctron** [comment]
It was easy to come up with a PR, so here is #12 .
