### ISSUE TITLE
Path support

### ISSUE THREAD

**Issue by ivarflakstad** [Dzordzu/rust-apache-age#3]
So far there is not support for path queries like `MATCH p=()-->() return p`.

The response from AGE looks a bit like this:
```js
[
  {"id": 1, "label": "Person", "properties": {"name": "Carl"}}::vertex,
  {"id": 100, "label": "family", "end_id": 2, "start_id": 1, "properties": {}}::edge,
  {"id": 2, "label": "Person", "properties": {"name": "Anna"}}::vertex
]::path
```

I have taken the liberty of creating some initial support for this (works locally with some tests), and I'm happy to share my work if you're interested 😊

**Comment by Dzordzu** [comment]
Merged
